# Direct Database Connection (Replace HOST and PASSWORD)
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.rezijlatjdjmmwsnkiwa
spring.datasource.password=5znLr1yRSNTtfSqN

# Supabase Keys (Replace SECRET_KEY)
supabase.url=https://rezijlatjdjmmwsnkiwa.supabase.co
supabase.service-role-key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlemlqbGF0amRqbW13c25raXdhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4ODg1NDU2NSwiZXhwIjoyMTA0NDMwNTY1fQ.vvoSxQTdDbm2Pr1ooA-TiLeyRzCa7r3Pv6RpzGgVirg
app.admin.registration-key=Nirbhay@19

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=8083